name: wireguard
version: '0.0.0'
synopsis: An example project
description: An example project
maintainer: Philipp Balzarek

dependencies:
  - base
  - aeson
  - async
  - bytestring
  - base64-bytestring
  - containers
  - data-default
  - exceptions
  - interpolate
  - lens
  - mtl
  - text
  - cryptonite
  - cereal
  - memory
  - random
  - time
  - unbounded-delays

default-extensions:
  - ApplicativeDo
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralisedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - UndecidableInstances
  - ViewPatterns

ghc-options:
    - -Wall
    - -Werror=incomplete-patterns
    - -Werror=incomplete-uni-patterns
    - -Werror=incomplete-record-updates

library:
  dependencies:
  - base
  source-dirs: src
  exposed-modules:
    - Wireguard
    - Wireguard.Crypto
    - Wireguard.Wire
    - Wireguard.Messages
    - Wireguard.Nonce
tests:
  tests:
    dependencies:
    - wireguard
    - hedgehog
    - tasty
    - hspec-hedgehog
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite

benchmarks:
  benchmark:
    dependencies:
      - wireguard
      - criterion
    main: Benchmark.hs
    source-dirs: benchmark
